


all :
	$(MAKE) -C Analyzer
	$(MAKE) -C Analyzer install 
	$(MAKE) -C Fit all install
	$(MAKE) -C SystematicFitter all install
	$(MAKE) -C Fitters all install
#	$(MAKE) -C HistAligner
#	$(MAKE) -C HistAligner install
#	$(MAKE) -C AlignSingleHist
#	$(MAKE) -C AlignSingleHist install
