/********************************************************************
* dictNuclearChart.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dictNuclearChart.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledictNuclearChart();
extern void G__cpp_setup_inheritancedictNuclearChart();
extern void G__cpp_setup_typetabledictNuclearChart();
extern void G__cpp_setup_memvardictNuclearChart();
extern void G__cpp_setup_globaldictNuclearChart();
extern void G__cpp_setup_memfuncdictNuclearChart();
extern void G__cpp_setup_funcdictNuclearChart();
extern void G__set_cpp_environmentdictNuclearChart();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "NuclearChart.h"
#include "Isotope.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictNuclearChartLN_TClass;
extern G__linked_taginfo G__dictNuclearChartLN_TBuffer;
extern G__linked_taginfo G__dictNuclearChartLN_TMemberInspector;
extern G__linked_taginfo G__dictNuclearChartLN_string;
extern G__linked_taginfo G__dictNuclearChartLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictNuclearChartLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictNuclearChartLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictNuclearChartLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictNuclearChartLN_Isotope;
extern G__linked_taginfo G__dictNuclearChartLN_NuclearChart;
extern G__linked_taginfo G__dictNuclearChartLN_maplEstringcOunsignedsPintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPintgRsPgRsPgR;
extern G__linked_taginfo G__dictNuclearChartLN_maplEunsignedsPintcOstringcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOstringgRsPgRsPgR;

/* STUB derived class for protected member access */
