
#include "G4String.hh"
#include "G4UserRunAction.hh"
#include "FragSimRunActionMessenger.hh"


#ifndef FRAGSIMRUNACTION_HH
#define FRAGSIMRUNACTION_HH 1

class G4Run;
class TreeMaker;

//! A class defining actions that are executed at the beginning and end of the run
/*!
 * This class is the concrete instance of the 
 * G4UserRunAction. It sets up the TreeMaker to 
 * analyze the events and can also be used to set
 * aspects of the run, like its user-given name,
 * 
 */
class FragSimRunAction : public G4UserRunAction
{
public:
  //! Default constructor
  /*!
   * The name of the run is set to "Test" so that
   * the file generated by the TreeMaker is Test.root.
   * A message is printed to the cout alerting the creation of FragSimRunAction.
   */
  FragSimRunAction();
  //! Constructor
  /*!
   * The name of the run is set using the passed G4String
   * so that the file generated by the TreeMaker is <run_name>.root.
   * A message is printed to the cout alerting the creation of FragSimRunAction.
   * @param run_name is the name of the run whose output is stored in <run_name>.root
   */
  FragSimRunAction(const G4String run_name);
  //! Destructor
  /*!
   * A message is printed to the cout alerting the destruction of FragSimRunAction. 
   */
  ~FragSimRunAction();
  //! Normal member function
  /*!
   * This function is called at the beginning of a run. It 
   * sets up the TTree named "Sim_Tree" that will be stored
   * in the output file <run_name>.root.
   * @param aRun is the current run
   */
  void BeginOfRunAction(const G4Run *aRun);
  //! Normal member function
  /*!
   * This function is called at the end of a run. It 
   * saves the TTree and closes the output file. It further
   * deletes the singleton instance of the TreeMaker.
   * 
   * @param aRun is the current run
   */  
  void EndOfRunAction(const G4Run *aRun);
  
  void SetRunName(G4String run_name);

private:
  //! Normal member function
  /*!
   * @return the number of events to simulate in the current run
   */ 
  G4int GetNumberOfEventsInRun(void);
  TreeMaker *ftreeMaker; //!< pointer to the TreeMaker singleton instance
  G4String    frun_name; //!< name of the run
  
  FragSimRunActionMessenger *messenger;
}; //END of class FragSimRunAction

#endif
