//
// File generated by rootcint at Tue Nov 29 13:57:11 2011

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "filebcgsLj.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TCollectionProxy.h"
#include "TIsAProxy.h"
// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

/********************************************************
* /home/coda/experiments/tompkins/pffrag2/analysis/./analysis_soft/Scripts/filebcgsLj.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablefilebcgsLj();

extern "C" void G__set_cpp_environmentfilebcgsLj() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/home/coda/experiments/tompkins/pffrag2/analysis/./analysis_soft/Scripts/SubtractBgnd.cpp");
  G__cpp_reset_tagtablefilebcgsLj();
}
#include <new>
extern "C" int G__cpp_dllrevfilebcgsLj() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */
static int G__filebcgsLj__0_1889(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TH1F*>* pobj;
         vector<TH1F*> xobj = GetAllHists(*(TFile*) libp->para[0].ref, (bool) G__int(libp->para[1]));
         pobj = new vector<TH1F*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__filebcgsLj__0_1890(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) IsNotADC((TH1F*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__filebcgsLj__0_1891(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      FilterOutTDC(*(vector<TH1F*>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__filebcgsLj__0_1892(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Reset((TH1F*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__filebcgsLj__0_1893(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      InspectSingleHistErrors((TH1F*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__filebcgsLj__0_1894(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GenerateConsistentHist((TH1F*) G__int(libp->para[0]), (TH1F*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__filebcgsLj__0_1895(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EnforceAxisRangeConsistency(*(vector<TH1F*>*) libp->para[0].ref, *(vector<TH1F*>*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__filebcgsLj__0_1896(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CalcErrors((TH1F*) G__int(libp->para[0]), (TH1F*) G__int(libp->para[1])
, (TH1F*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__filebcgsLj__0_1897(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SubtractBgndRuns((TFile*) G__int(libp->para[0]), (TFile*) G__int(libp->para[1])
, (const Char_t*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncfilebcgsLj {
 public:
  G__Sizep2memfuncfilebcgsLj() {p=&G__Sizep2memfuncfilebcgsLj::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncfilebcgsLj::*p)();
};

size_t G__get_sizep2memfuncfilebcgsLj()
{
  G__Sizep2memfuncfilebcgsLj a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancefilebcgsLj() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablefilebcgsLj() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,Int_t>",117,G__get_linked_tagnum(&G__filebcgsLjLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ConfigEntry*>",117,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1*>",117,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,Version_t>",117,G__get_linked_tagnum(&G__filebcgsLjLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,short>",117,G__get_linked_tagnum(&G__filebcgsLjLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,short,less<void*>>",117,G__get_linked_tagnum(&G__filebcgsLjLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__filebcgsLjLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__filebcgsLjLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1F*>",117,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarfilebcgsLj() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncfilebcgsLj() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
   G__memvar_setup((void*)(&fnm),117,0,0,G__get_linked_tagnum(&G__filebcgsLjLN_FNameManager),-1,-1,1,"fnm=",0,(char*)NULL);
   G__memvar_setup((void*)(&acm),117,0,0,G__get_linked_tagnum(&G__filebcgsLjLN_ConfigManager),-1,-1,1,"acm=",0,(char*)NULL);

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalfilebcgsLj() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
   G__memfunc_setup("GetAllHists", 1092, G__filebcgsLj__0_1889, 117, G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR), G__defined_typename("vector<TH1F*>"), 0, 2, 1, 1, 0, 
"u 'TFile' - 1 - rootfile g - - 0 - stringent", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("IsNotADC", 693, G__filebcgsLj__0_1890, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "U 'TH1F' - 0 - h", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("FilterOutTDC", 1145, G__filebcgsLj__0_1891, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<TH1F*,allocator<TH1F*> >' 'vector<TH1F*>' 1 - vec", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("Reset", 515, G__filebcgsLj__0_1892, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TH1F' - 0 - h", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("InspectSingleHistErrors", 2381, G__filebcgsLj__0_1893, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TH1F' - 0 - h", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("GenerateConsistentHist", 2285, G__filebcgsLj__0_1894, 85, G__get_linked_tagnum(&G__filebcgsLjLN_TH1F), -1, 0, 2, 1, 1, 0, 
"U 'TH1F' - 0 - hbg U 'TH1F' - 0 - hprod", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EnforceAxisRangeConsistency", 2774, G__filebcgsLj__0_1895, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<TH1F*,allocator<TH1F*> >' 'vector<TH1F*>' 1 - hbg u 'vector<TH1F*,allocator<TH1F*> >' 'vector<TH1F*>' 1 - hprod", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("CalcErrors", 1008, G__filebcgsLj__0_1896, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'TH1F' - 0 - hcl U 'TH1F' - 0 - hbg "
"U 'TH1F' - 0 - h", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("SubtractBgndRuns", 1643, G__filebcgsLj__0_1897, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'TFile' - 0 - fbg U 'TFile' - 0 - fprod "
"C - 'Char_t' 10 - foutname", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcfilebcgsLj() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__filebcgsLjLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_ConfigManager = { "ConfigManager" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_vectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgR = { "vector<ConfigEntry*,allocator<ConfigEntry*> >" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_reverse_iteratorlEvectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ConfigEntry*,allocator<ConfigEntry*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_FNameManager = { "FNameManager" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR = { "vector<TH1*,allocator<TH1*> >" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1*,allocator<TH1*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR = { "multimap<void*,short,less<void*>,allocator<pair<void* const,short> > >" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR = { "vector<TH1F*,allocator<TH1F*> >" , 99 , -1 };
G__linked_taginfo G__filebcgsLjLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1F*,allocator<TH1F*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablefilebcgsLj() {
  G__filebcgsLjLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__filebcgsLjLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__filebcgsLjLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__filebcgsLjLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__filebcgsLjLN_TFile.tagnum = -1 ;
  G__filebcgsLjLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR.tagnum = -1 ;
  G__filebcgsLjLN_ConfigManager.tagnum = -1 ;
  G__filebcgsLjLN_vectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgR.tagnum = -1 ;
  G__filebcgsLjLN_reverse_iteratorlEvectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__filebcgsLjLN_FNameManager.tagnum = -1 ;
  G__filebcgsLjLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR.tagnum = -1 ;
  G__filebcgsLjLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__filebcgsLjLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR.tagnum = -1 ;
  G__filebcgsLjLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__filebcgsLjLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__filebcgsLjLN_TH1F.tagnum = -1 ;
  G__filebcgsLjLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR.tagnum = -1 ;
  G__filebcgsLjLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablefilebcgsLj() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__filebcgsLjLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_TFile);
   G__get_linked_tagnum(&G__filebcgsLjLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_ConfigManager);
   G__get_linked_tagnum(&G__filebcgsLjLN_vectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_FNameManager);
   G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_TVectorTlEfloatgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_TVectorTlEdoublegR);
   G__get_linked_tagnum(&G__filebcgsLjLN_TH1F);
   G__get_linked_tagnum(&G__filebcgsLjLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR);
   G__get_linked_tagnum(&G__filebcgsLjLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupfilebcgsLj(void) {
  G__check_setup_version(30051515,"G__cpp_setupfilebcgsLj()");
  G__set_cpp_environmentfilebcgsLj();
  G__cpp_setup_tagtablefilebcgsLj();

  G__cpp_setup_inheritancefilebcgsLj();

  G__cpp_setup_typetablefilebcgsLj();

  G__cpp_setup_memvarfilebcgsLj();

  G__cpp_setup_memfuncfilebcgsLj();
  G__cpp_setup_globalfilebcgsLj();
  G__cpp_setup_funcfilebcgsLj();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncfilebcgsLj();
  return;
}
class G__cpp_setup_initfilebcgsLj {
  public:
    G__cpp_setup_initfilebcgsLj() { G__add_setup_func("filebcgsLj",(G__incsetup)(&G__cpp_setupfilebcgsLj)); G__call_setup_funcs(); }
   ~G__cpp_setup_initfilebcgsLj() { G__remove_setup_func("filebcgsLj"); }
};
G__cpp_setup_initfilebcgsLj G__cpp_setup_initializerfilebcgsLj;

