// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /home/coda/experiments/tompkins/pffrag2/analysis/./analysis_soft/Scripts/SubtractBgnd.cpp;

#endif
