/********************************************************************
* /home/coda/experiments/tompkins/pffrag2/analysis/./analysis_soft/Scripts/filebcgsLj.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/coda/experiments/tompkins/pffrag2/analysis/./analysis_soft/Scripts/filebcgsLj.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablefilebcgsLj();
extern void G__cpp_setup_inheritancefilebcgsLj();
extern void G__cpp_setup_typetablefilebcgsLj();
extern void G__cpp_setup_memvarfilebcgsLj();
extern void G__cpp_setup_globalfilebcgsLj();
extern void G__cpp_setup_memfuncfilebcgsLj();
extern void G__cpp_setup_funcfilebcgsLj();
extern void G__set_cpp_environmentfilebcgsLj();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "/home/coda/experiments/tompkins/pffrag2/analysis/./analysis_soft/Scripts/SubtractBgnd.cpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__filebcgsLjLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__filebcgsLjLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__filebcgsLjLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__filebcgsLjLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__filebcgsLjLN_TFile;
extern G__linked_taginfo G__filebcgsLjLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__filebcgsLjLN_ConfigManager;
extern G__linked_taginfo G__filebcgsLjLN_vectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgR;
extern G__linked_taginfo G__filebcgsLjLN_reverse_iteratorlEvectorlEConfigEntrymUcOallocatorlEConfigEntrymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__filebcgsLjLN_FNameManager;
extern G__linked_taginfo G__filebcgsLjLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR;
extern G__linked_taginfo G__filebcgsLjLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__filebcgsLjLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__filebcgsLjLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__filebcgsLjLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__filebcgsLjLN_TH1F;
extern G__linked_taginfo G__filebcgsLjLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR;
extern G__linked_taginfo G__filebcgsLjLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
